### ISSUE TITLE
Turn About Modal into Settings Modal

### ISSUE THREAD

**Issue by felixrieseberg** [azure-storage/deco#184]
Also, figure out a simple way to not have the modal on the page all the time - and give it it's own controller.

**Comment by sedouard** [comment]
when this is closed, it should also close https://github.com/azure-storage/xplat/issues/64

**Comment by sedouard** [comment]
closed via https://github.com/azure-storage/deco/commit/364ce823f8aa572ef72df51688a935c9213c7b68
