### ISSUE TITLE
Add AppVeyor to our CI pipeline

### ISSUE THREAD

**Issue by felixrieseberg** [azure-storage/deco#318]
Currently, we're building our dev builds on linux - meaning that Windows builds don't contain any icons, without an installer, and without other `rcedit.exe`-controlled details. If somebody were to setup AppVeyor, we could use Travis for OS X/Linux builds - and AppVeyor for Windows builds. Plus, we'd gain Windows testing.

**Comment by felixrieseberg** [comment]
Almost there - just figuring out how to have it build a Windows Installer for us.

**Comment by felixrieseberg** [comment]
Quick update, especially for @sedouard: Windows Testing is sort of a non-starter. I've been trying to wrap my head around the stdout mess, but it's sooo hard that I feel like we should just be happy with full testing on Travis - I still want to use AppVeyor to compile dev builds with icons (and other metadata), which works just fine.

**Comment by sedouard** [comment]
We have no OS-specific features we take on during testing. Still, it would be nice to have the test suite run on windows. I'll follow up with @traceyt, she's been deving on Windows and (at one point) had tests running.

**Comment by sedouard** [comment]
gonna close this one as I think its OK to not run tests on windows right now.
