### ISSUE TITLE
Adding new account then click "add and open" opens the 'default' storage account

### ISSUE THREAD

**Issue by cicorias** [azure-storage/deco#329]
I had 2 existing storage accounts setup. I then added another storage account name and key. Then i clicked "add & open" and it opened on the 'default' account (the account that was listed i think or the one i last opened during a session).

I would expect it to open the account I just added.

**Comment by sedouard** [comment]
@cicorias thanks for reporting. I can't seem to reproduce the behavior (have plenty of accounts, add a new one, click 'Save + Open ' and it opens the recently added account). Which version are you running, the last release, source, or live build?

**Comment by cicorias** [comment]
release build. i'll try with dev perhaps it's been fixed and close this now...
