### ISSUE TITLE
[Feature] Ability to set policy on a container

### ISSUE THREAD

**Issue by cicorias** [azure-storage/deco#330]
Ability to set a policy on a container - such as public or other policies which allow using that policy for members of the container - and SAS generation for R/W access.

**Comment by sedouard** [comment]
Container policy - Blob or Container:
![](http://g.recordit.co/akPElQ9AXG.gif)

SAS Generation:
![](http://recordit.co/7dhv7xFzs6/gif/notify)

Are these not sufficient @cicorias? Or is this just a feature discovery issue?

**Comment by cicorias** [comment]
more than sufficient - didn't know it existed :+1:

**Comment by sedouard** [comment]
No worries. I've been adding a bunch of features in the modals and we haven't really highlighted them on our landing page just yet.
