### ISSUE TITLE
[bug] container names are showing uppercase although they are lowercase

### ISSUE THREAD

**Issue by cicorias** [azure-storage/deco#332]
The container names are being forced upper case in the left hand pane.

**Comment by felixrieseberg** [comment]
Thanks for reporting! That's not exactly a bug, just us trying to sick to Azure's designguideines for navigation panes.

"That's a feature, not a bug" ;-)

**Comment by cicorias** [comment]
which design guide? on Ibiza portal all show in proper case (lowercase)?

**Comment by felixrieseberg** [comment]
I was talking about the branding we had when this thing was created (see below). Besides, all container names are caseless anyway (there's no upper- or lowercase), so this is a pure design decision. For the moment, I'd rather not change design - given how many things we have that are actually pressing issues.

<img width="1115" alt="screen shot 2015-09-13 at 1 37 31 pm" src="https://cloud.githubusercontent.com/assets/1426799/9838859/9f038368-5a1c-11e5-927a-957610ae1535.png">

**Comment by cicorias** [comment]
hmm. wouldn't it then just be on the backlog w/ a low priority?

i guess as a user of the tool, i'd expect to see the proper casing, if I attempt to use the upper case that will toss a 404 or exception as it doesn't exist and violates the rules

**Comment by felixrieseberg** [comment]
I'm on vacation right now, so i'll just leave it at this: We should totally ensure that we treat names as lowercase only. The nav menu on the left is a design thing and not part of any logic.

For now, I closed this issue as "won't fix", because I certainly don't want to change presentation right now (except for added features). We can talk about this again if/when we overhaul design overall.

**Comment by sedouard** [comment]
@cicorias I have to agree here. From a UX perspective, creating a container with uppercases will convert into lower cases so even attempting to have upper casing will result in expected behavior. The notification bar will confirm the creation as well.

**Comment by cicorias** [comment]
I did try to create with uppercase and the UX didn't respond; i had assumed it went into some timeout somewhere..  It may be in the dev build; i was trying via the release build...  I'll try again with the dev build.
