### ISSUE TITLE
Getting a blue screen on the Mac App

### ISSUE THREAD

**Issue by IntricatePixels** [azure-storage/deco#368]
I downloaded the app for Mac today and it was working well just an hour ago, but at the moment when I launch the app, all I see is a blue screen.  Azure Storage seems to be up as I can connect to it using Cyberduck.

**Comment by sedouard** [comment]
thanks @IntricatePixels! we're taking a look into what's causing the bad build.

You should be able to open the release version successfully.

**Comment by gmarchet** [comment]
Alas no, not even version 0.5.1 opens successfully on OS X 10.11.1. The Windows version does.

**Comment by sedouard** [comment]
@IntricatePixels, @gmarchet did you happen to upgrade or was this the first time you used the explorer?

**Comment by felixrieseberg** [comment]
@sedouard: I guess we'll have a fix out tomorrow :cake:

**Comment by sedouard** [comment]
lol

**Comment by gmarchet** [comment]
I upgraded on the Mac, but it was the first time on Windows or Linux
G.

**Comment by IntricatePixels** [comment]
First time install for me on a Mac, no upgrade. Version 0.32.1

**Comment by felixrieseberg** [comment]
If you go to the website now (storageexplorer.com), you two will find a nice surprise - a new major version. It should fix all your issues, so I'm closing this for now :wink: 

Thanks for reporting!
